Repository epinowcast/epinowcast, pull requests merged in 2022-07, with the labels that each got.

#84 Feature: exponential delays
  DESCRIPTION
  NEWS.md
  R/model-tools.R
  R/model.R
  R/preprocess.R
  inst/stan/chunks/debug.stan
  inst/stan/epinowcast.stan
  inst/stan/functions/discretised_reporting_prob.stan
  inst/stan/functions/expected_obs.stan
  inst/stan/functions/expected_obs_from_index.stan
  inst/stan/functions/obs_lpmf.stan
  man/enw_as_data_list.Rd
  man/enw_inits.Rd
  man/enw_opts_as_data_list.Rd
  man/epinowcast-package.Rd
  man/epinowcast.Rd
  tests/testthat/_snaps/enw_inits.md
  tests/testthat/test-enw_inits.R
Labels: enhancement

#103 Feature cumulative sum expectation
  .github/workflows/R-CMD-check.yaml
  .github/workflows/test-coverage.yaml
  NEWS.md
  R/preprocess.R
  inst/stan/epinowcast.stan
  tests/testthat/test-enw_model.R
Labels: bug, enhancement, high-priority

#113 Update discretised_reporting_prob
  NEWS.md
  inst/stan/epinowcast.stan
  inst/stan/functions/discretised_reporting_prob.stan
Labels: enhancement

#121 Roll back to excluding data beyond the maximum delay
  NEWS.md
  R/preprocess.R
  inst/stan/epinowcast.stan
  man/enw_preprocess_data.Rd
  vignettes/model.Rmd
Labels: bug

#120 Feature: Add support for Poisson observation models
  .pre-commit-config.yaml
  NEWS.md
  R/model-modules.R
  README.md
  figures/ind_nowcast-1.png
  figures/unnamed-chunk-20-1.png
  inst/WORDLIST
  inst/examples/germany_simple.R
  inst/extdata/nowcast.rds
  inst/stan/chunks/debug.stan
  inst/stan/epinowcast.stan
  inst/stan/functions/obs_lpmf.stan
  man/enw_obs.Rd
  man/figures/README-nowcast-1.png
  man/figures/README-pp-1.png
  man/figures/README-week_nowcast-1.png
  tests/testthat/_snaps/enw_obs.md
  tests/testthat/test-enw_obs.R
  tests/testthat/test-epinowcast.R
  vignettes/model.Rmd
Labels: enhancement

#128 Add loglogistic parametric distribution
  NEWS.md
  R/model-modules.R
  inst/stan/epinowcast.stan
  inst/stan/functions/discretised_reporting_prob.stan
  man/enw_reference.Rd
  tests/testthat/test-enw_reference.R
Labels: enhancement

#132 Feature improve news
  .gitignore
  DESCRIPTION
  NEWS.md
Labels: documentation, enhancement

#137 Feature modularise observations
  NEWS.md
  README.md
  inst/WORDLIST
  inst/stan/epinowcast.stan
  inst/stan/functions/combine_logit_hazards.stan
  inst/stan/functions/delay_lpmf.stan
  inst/stan/functions/expected_obs.stan
  inst/stan/functions/expected_obs_from_index.stan
  inst/stan/functions/obs_lpmf.stan
  inst/stan/functions/regression.stan
  man/epinowcast-package.Rd
  man/figures/README-nowcast-1.png
  man/figures/README-pp-1.png
  man/figures/README-week_nowcast-1.png
Labels: enhancement

#134 Hazard specification of parametric baseline hazard
  NEWS.md
  inst/extdata/nowcast.rds
  inst/stan/chunks/debug.stan
  inst/stan/epinowcast.stan
  inst/stan/functions/discretised_reporting_prob.stan
Labels: enhancement, high-priority

#142 Bug: ref_as_p not activating
  NEWS.md
  R/model-modules.R
  inst/stan/epinowcast.stan
  tests/testthat/test-enw_reference.R
  tests/testthat/test-enw_report.R
Labels: bug

#140 Feature logit reference hazard
  NEWS.md
  R/utils.R
  README.md
  inst/examples/germany_dow.R
  inst/stan/chunks/debug.stan
  inst/stan/epinowcast.stan
  inst/stan/functions/discretised_logit_hazard.stan
  inst/stan/functions/discretised_reporting_prob.stan
  inst/stan/functions/expected_obs.stan
  man/figures/README-nowcast-1.png
  man/figures/README-pp-1.png
  man/figures/README-week_nowcast-1.png
  tests/testthat/test-enw_reference.R
  tests/testthat/test-stan_discretised_logit_hazard.R
Labels: enhancement, help wanted
