Repository epinowcast/epinowcast, pull requests merged in 2023-05, with the labels that each got.

#267 Issue 260: Refactoring the README
  .github/workflows/render-readme.yaml
  DESCRIPTION
  NEWS.md
  README.Rmd
  README.md
  inst/CITATION
  man/figures/README-nowcast-1.png
  man/figures/README-pp-1.png
  man/figures/README-week_nowcast-1.png
Labels: documentation, enhancement

#276 Issue 273: Use array syntax for initial conditions in order to work with cmdstan 2.32.1
  .github/workflows/R-CMD-check.yaml
  DESCRIPTION
  NEWS.md
  R/model-modules.R
Labels: bug, high-priority, self-reviewed

#275 Issue 278: minor improvements to the discrete delay distributions vignette
  DESCRIPTION
  NEWS.md
  vignettes/distributions.Rmd
Labels: documentation

#274 Issue 279: Improved enw_preprocess_data documentation and input checking
  DESCRIPTION
  NEWS.md
  R/preprocess.R
  man/enw_complete_dates.Rd
  man/enw_construct_data.Rd
  man/enw_delay_filter.Rd
  man/enw_delay_metadata.Rd
  man/enw_preprocess_data.Rd
  man/enw_reference_by_report.Rd
  man/enw_reps_with_complete_refs.Rd
  man/enw_score_nowcast.Rd
  man/epinowcast-package.Rd
  man/epinowcast.Rd
  tests/testthat/test-enw_preprocess_data.R
Labels: documentation

#280 0.2.2 release
  DESCRIPTION
  NEWS.md
Labels: infrastructure

#282 Issue 281: Mismatch in dimension declared and found in context when models specified with multiple timeseries
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/model-modules.R
  tests/testthat/_snaps/enw_expectation.md
  tests/testthat/test-enw_expectation.R
  tests/testthat/test-epinowcast.R
  touchstone/.gitignore
  touchstone/multigroup-setup.R
  touchstone/script.R
Labels: bug, self-reviewed
