Repository epinowcast/epinowcast, pull requests merged in 2023-04, with the labels that each got.

#232 `enw_metadata()` `target_date` default be detected from the function specification
  DESCRIPTION
  NEWS.md
  R/preprocess.R
  man/enw_metadata.Rd
  man/epinowcast-package.Rd
  tests/testthat/test-enw_metadata.R
Labels: enhancement

#229 Do not use else after stop()
  DESCRIPTION
  NEWS.md
  R/check.R
  R/preprocess.R
Labels: enhancement

#236 Updates citation file with new authors
  NEWS.md
  README.md
  inst/CITATION
  man/figures/README-nowcast-1.png
  man/figures/README-pp-1.png
  man/figures/README-week_nowcast-1.png
Labels: documentation, enhancement

#237 Update CITATION to use bibentry
  NEWS.md
  README.md
  inst/CITATION
  man/figures/README-nowcast-1.png
  man/figures/README-pp-1.png
  man/figures/README-week_nowcast-1.png
Labels: documentation, enhancement

#256 Issue 250: Ground work to shift development to `main` from `develop`
  .github/workflows/render-readme.yaml
  CONTRIBUTING.md
  DESCRIPTION
  NEWS.md
  README.Rmd
  README.md
  man/figures/README-nowcast-1.png
  man/figures/README-pp-1.png
  man/figures/README-week_nowcast-1.png
Labels: enhancement, infrastructure

#254 Issue 245: Cleaning enw_formula_as_data_list() to align with DRY principles (#245)
  DESCRIPTION
  NEWS.md
  R/model-tools.R
Labels: enhancement, new-contributor

#264 Issue 211: Style guide first draft
  .Rbuildignore
  CONTRIBUTING.md
  DESCRIPTION
  NEWS.md
  STYLE_GUIDE.md
Labels: documentation, high-priority

#265 Issue 129: Better document delay distribution modeling
  DESCRIPTION
  NEWS.md
  R/epinowcast.R
  R/preprocess.R
  README.Rmd
  README.md
  _pkgdown.yml
  codemeta.json
  inst/stan/epinowcast.stan
  inst/stan/functions/combine_logit_hazards.stan
  inst/stan/functions/delay_lpmf.stan
  inst/stan/functions/expected_obs.stan
  man/enw_filter_reference_dates.Rd
  man/enw_score_nowcast.Rd
  man/epinowcast-package.Rd
  man/epinowcast.Rd
  man/figures/README-nowcast-1.png
  man/figures/README-pp-1.png
  man/figures/README-week_nowcast-1.png
  vignettes/distributions.Rmd
  vignettes/germany-age-stratified-nowcasting.Rmd
  vignettes/germany-age-stratified-nowcasting.Rmd.orig
  vignettes/model.Rmd
Labels: documentation
